<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="14.0.0" />
    <PackageReference Include="FluentValidation" Version="11.11.0" />
    <PackageReference Include="MediatR" Version="12.4.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.2" />
    <PackageReference Include="Quartz" Version="3.13.1" />
    <PackageReference Include="Quartz.AspNetCore" Version="3.13.1" />
    <PackageReference Include="Quartz.Extensions.Hosting" Version="3.13.1" />
    <PackageReference Include="Quartz.Jobs" Version="3.13.1" />
    <PackageReference Include="System.Security.Claims" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SalesTrack.Abstractions\SalesTrack.Abstractions.csproj" />
    <ProjectReference Include="..\SalesTrack.Common\SalesTrack.Common.csproj" />
    <ProjectReference Include="..\SalesTrack.Domain\SalesTrack.Domain.csproj" />
    <ProjectReference Include="..\SalesTrack.Infrastructure\SalesTrack.Infrastructure.csproj" />
    <ProjectReference Include="..\SalesTrack.Persistence\SalesTrack.Persistence.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Jobs\" />
    <Folder Include="Services\" />
  </ItemGroup>

</Project>
